### ISSUE TITLE
Crash when repositories are removed from installation

### ISSUE THREAD

**Issue by bartekpacia** [bee-ci-system/bee-ci#46]
```
[server] [2024-10-20 22:16:45] 22:16:45 INF http: panic serving 10.244.0.72:37334: reflect: call of github.com/jmoiron/sqlx/reflectx.(*Mapper).TraversalsByNameFunc on slice Value
[server] [2024-10-20 22:16:45] goroutine 1551 [running]:
[server] [2024-10-20 22:16:45] net/http.(*conn).serve.func1()
[server] [2024-10-20 22:16:45]  /usr/local/go/src/net/http/server.go:1947 +0x13f
[server] [2024-10-20 22:16:45] panic({0xcedbe0?, 0xc0000104e0?})
[server] [2024-10-20 22:16:45]  /usr/local/go/src/runtime/panic.go:785 +0x136
[server] [2024-10-20 22:16:45] github.com/jmoiron/sqlx/reflectx.mustBe({0x7ebd138e9740, 0xcba480}, 0x19)
[server] [2024-10-20 22:16:45]  /go/pkg/mod/github.com/jmoiron/sqlx@v1.4.0/reflectx/reflect.go:248 +0xa5
[server] [2024-10-20 22:16:45] github.com/jmoiron/sqlx/reflectx.(*Mapper).TraversalsByNameFunc(0xc00020a120, {0xe65900, 0xcba480}, {0xc00014a140, 0x1, 0xa}, 0xc0002d59c8)
[server] [2024-10-20 22:16:45]  /go/pkg/mod/github.com/jmoiron/sqlx@v1.4.0/reflectx/reflect.go:186 +0xd5
[server] [2024-10-20 22:16:45] github.com/jmoiron/sqlx.bindArgs({0xc00014a140, 0x1, 0xa}, {0xcba480, 0xc0000104c8}, 0xc00020a120)
[server] [2024-10-20 22:16:45]  /go/pkg/mod/github.com/jmoiron/sqlx@v1.4.0/named.go:182 +0x2f4
[server] [2024-10-20 22:16:45] github.com/jmoiron/sqlx.bindAnyArgs({0xc00014a140, 0x1, 0xa}, {0xcba480, 0xc0000104c8}, 0xc00020a120)
[server] [2024-10-20 22:16:45]  /go/pkg/mod/github.com/jmoiron/sqlx@v1.4.0/named.go:167 +0x21b
[server] [2024-10-20 22:16:45] github.com/jmoiron/sqlx.(*NamedStmt).ExecContext(0xc0000bf530, {0xe60e60, 0xc0000bf260}, {0xcba480, 0xc0000104c8})
[server] [2024-10-20 22:16:45]  /go/pkg/mod/github.com/jmoiron/sqlx@v1.4.0/named_context.go:38 +0xe5
[server] [2024-10-20 22:16:45] github.com/bee-ci/bee-ci-system/internal/data.PostgresRepoRepo.Delete({0xc00020a150}, {0xe60e60, 0xc0000bf260}, {0xc000097b00, 0x8b, 0x8b})
[server] [2024-10-20 22:16:45]  /tmp/server/internal/data/repo_repo.go:72 +0x41c
[server] [2024-10-20 22:16:45] github.com/bee-ci/bee-ci-system/internal/server/webhook.WebhookHandler.handleWebhook({0xc0000be240, {0xe5fd28, 0xc0000c8018}, {0xe60e28, 0xc0000c8020}, {0xe62cb8, 0xc0000c8010}, {0xc00002803c, 0xb}, {0xc00003
```

**Comment by bartekpacia** [comment]
I fixed this today
